// flow-typed signature: 5355f368bb18a196e3871e7ee4c1c0fa
// flow-typed version: <<STUB>>/babel-plugin-flow-comments_v^6.3.19/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-flow-comments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-flow-comments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-flow-comments/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-flow-comments/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-flow-comments/lib/index'>;
}
